from datetime import date
from schemas.event import EventOut
from schemas.user import UserInfo

mock_events = [
    # Upcoming Events
    EventOut(
        id=1,
        title="Hack the Future",
        description="A hackathon for all skill levels.",
        date=date(2025, 7, 20),
        location="IC Building, Room 402",
        image_url="https://example.com/hack.jpg",
        is_public=True,
        departments=["Computer Science"],
        categories=["Hackathon"],
        clubs=["AMACSS"],
        types=["Competition"],
        user=UserInfo(id=1, username="amacss_admin", pfp_url=""),
    ),
    EventOut(
        id=2,
        title="Math Puzzle Night",
        description="Collaborative math challenges and prizes.",
        date=date(2025, 6, 10),
        location="Science Wing 115",
        image_url="https://example.com/math.jpg",
        is_public=True,
        departments=["Mathematics"],
        categories=["Puzzle"],
        clubs=["Mathematics Club"],
        types=["Social"],
        user=UserInfo(id=2, username="math_user", pfp_url=""),
    ),
    EventOut(
        id=3,
        title="Coding Bootcamp",
        description="Beginner-friendly JavaScript course.",
        date=date(2025, 6, 15),
        location="Online (Zoom)",
        image_url="https://example.com/bootcamp.jpg",
        is_public=True,
        departments=["Computer Science"],
        categories=["Workshop"],
        clubs=["CSEC"],
        types=["Learning"],
        user=UserInfo(id=3, username="csec_lead", pfp_url=""),
    ),

    # Latest Events
    EventOut(
        id=4,
        title="Speed Coding Challenge",
        description="Code fast, win prizes!",
        date=date(2025, 6, 1),
        location="IC-402",
        image_url="https://example.com/speed.jpg",
        is_public=True,
        departments=["Computer Science"],
        categories=["Competition"],
        clubs=["Programming Club"],
        types=["Challenge"],
        user=UserInfo(id=4, username="prog_master", pfp_url=""),
    ),
    EventOut(
        id=5,
        title="Math Jeopardy!",
        description="Test your math skills in a Jeopardy format.",
        date=date(2025, 5, 28),
        location="SW-105",
        image_url="https://example.com/jeopardy.jpg",
        is_public=True,
        departments=["Mathematics"],
        categories=["Game Night"],
        clubs=["Mathematics Club"],
        types=["Trivia"],
        user=UserInfo(id=2, username="math_user", pfp_url=""),
    ),

    # Recently Added Events
    EventOut(
        id=6,
        title="Cybersecurity Basics",
        description="Workshop on staying safe online.",
        date=date(2025, 6, 18),
        location="IC Lab 3",
        image_url="https://example.com/cyber.jpg",
        is_public=True,
        departments=["Computer Science"],
        categories=["Workshop"],
        clubs=["CSEC"],
        types=["Learning"],
        user=UserInfo(id=3, username="csec_admin", pfp_url=""),
    ),
    EventOut(
        id=7,
        title="Python Practice",
        description="Solve coding challenges in Python.",
        date=date(2025, 6, 5),
        location="IC 404",
        image_url="https://example.com/python.jpg",
        is_public=True,
        departments=["Computer Science"],
        categories=["Practice"],
        clubs=["Programming Club"],
        types=["Challenge"],
        user=UserInfo(id=5, username="prog_enthusiast", pfp_url=""),
    ),

    # Past Events
    EventOut(
        id=8,
        title="Intro to Linux",
        description="A past event teaching Linux basics.",
        date=date(2025, 3, 15),
        location="SW-210",
        image_url="https://example.com/linux.jpg",
        is_public=False,
        departments=["Computer Science"],
        categories=["Workshop"],
        clubs=["CSEC"],
        types=["Learning"],
        user=UserInfo(id=9, username="techie_tim", pfp_url=""),
    ),
    EventOut(
        id=9,
        title="Fun with Logic",
        description="Math games based on logical reasoning.",
        date=date(2025, 2, 28),
        location="SW-120",
        image_url="https://example.com/logic.jpg",
        is_public=True,
        departments=["Mathematics"],
        categories=["Games"],
        clubs=["Mathematics Club"],
        types=["Educational"],
        user=UserInfo(id=10, username="math_admin", pfp_url=""),
    ),

    # Clubs-Based Filtering
    EventOut(
        id=10,
        title="Git and GitHub Basics",
        description="Learn version control with Git.",
        date=date(2025, 6, 22),
        location="IC-410",
        image_url="https://example.com/git.jpg",
        is_public=True,
        departments=["Computer Science"],
        categories=["Workshop"],
        clubs=["CSEC"],
        types=["Learning"],
        user=UserInfo(id=3, username="csec_lead", pfp_url=""),
    ),
    EventOut(
        id=11,
        title="Game Jam 2025",
        description="24-hour game dev event.",
        date=date(2025, 7, 10),
        location="IC Atrium",
        image_url="https://example.com/gamejam.jpg",
        is_public=True,
        departments=["Computer Science"],
        categories=["Hackathon"],
        clubs=["Programming Club"],
        types=["Competition"],
        user=UserInfo(id=4, username="prog_master", pfp_url=""),
    ),
    EventOut(
        id=12,
        title="Math Careers Panel",
        description="Hear from alumni in math careers.",
        date=date(2025, 6, 8),
        location="Science Lecture Hall",
        image_url="https://example.com/career.jpg",
        is_public=True,
        departments=["Mathematics"],
        categories=["Panel"],
        clubs=["Mathematics Club"],
        types=["Networking"],
        user=UserInfo(id=2, username="math_user", pfp_url=""),
    ),

    # Diverse Dates
    EventOut(
        id=13,
        title="Women in Tech Panel",
        description="Empowering women in CS.",
        date=date(2025, 5, 25),
        location="Online",
        image_url="https://example.com/women.jpg",
        is_public=True,
        departments=["Computer Science"],
        categories=["Panel"],
        clubs=["AMACSS"],
        types=["Awareness"],
        user=UserInfo(id=1, username="amacss_admin", pfp_url=""),
    ),
    EventOut(
        id=14,
        title="Algorithm Workshop",
        description="Learn sorting algorithms.",
        date=date(2025, 6, 30),
        location="IC-312",
        image_url="https://example.com/algo.jpg",
        is_public=True,
        departments=["Computer Science"],
        categories=["Workshop"],
        clubs=["Programming Club"],
        types=["Educational"],
        user=UserInfo(id=6, username="prog_user", pfp_url=""),
    ),
    EventOut(
        id=15,
        title="Math Research Talk",
        description="Undergraduate math research showcase.",
        date=date(2025, 6, 2),
        location="SW-205",
        image_url="https://example.com/research.jpg",
        is_public=True,
        departments=["Mathematics"],
        categories=["Talk"],
        clubs=["Mathematics Club"],
        types=["Academic"],
        user=UserInfo(id=2, username="math_user", pfp_url=""),
    ),

    # Additional Mix
    EventOut(
        id=16,
        title="Code Golf Night",
        description="Solve problems with the shortest code.",
        date=date(2025, 6, 27),
        location="IC Lab 1",
        image_url="https://example.com/golf.jpg",
        is_public=True,
        departments=["Computer Science"],
        categories=["Competition"],
        clubs=["Programming Club"],
        types=["Game"],
        user=UserInfo(id=4, username="prog_master", pfp_url=""),
    ),
    EventOut(
        id=17,
        title="Data Science Demystified",
        description="Intro to data science methods.",
        date=date(2025, 7, 5),
        location="IC 110",
        image_url="https://example.com/data.jpg",
        is_public=True,
        departments=["Computer Science"],
        categories=["Talk"],
        clubs=["AMACSS"],
        types=["Educational"],
        user=UserInfo(id=1, username="amacss_admin", pfp_url=""),
    ),
    EventOut(
        id=18,
        title="Discrete Math Review",
        description="Finals prep session for MATB24.",
        date=date(2025, 6, 1),
        location="SW-112",
        image_url="https://example.com/discrete.jpg",
        is_public=True,
        departments=["Mathematics"],
        categories=["Study Session"],
        clubs=["Mathematics Club"],
        types=["Review"],
        user=UserInfo(id=10, username="math_ta", pfp_url=""),
    ),
    EventOut(
        id=19,
        title="Intro to Web Dev",
        description="Learn HTML/CSS/JS basics.",
        date=date(2025, 6, 11),
        location="IC-406",
        image_url="https://example.com/web.jpg",
        is_public=True,
        departments=["Computer Science"],
        categories=["Workshop"],
        clubs=["CSEC"],
        types=["Learning"],
        user=UserInfo(id=3, username="csec_lead", pfp_url=""),
    ),
    EventOut(
        id=20,
        title="Functional Programming",
        description="Haskell intro night.",
        date=date(2025, 5, 30),
        location="Online",
        image_url="https://example.com/haskell.jpg",
        is_public=True,
        departments=["Computer Science"],
        categories=["Workshop"],
        clubs=["Programming Club"],
        types=["Educational"],
        user=UserInfo(id=5, username="prog_enthusiast", pfp_url=""),
    ),
    EventOut(
        id=21,
        title="Late Night Leetcode",
        description="Group problem solving session.",
        date=date(2025, 6, 20),
        location="IC Lab 2",
        image_url="https://example.com/leetcode.jpg",
        is_public=True,
        departments=["Computer Science"],
        categories=["Study"],
        clubs=["Programming Club"],
        types=["Practice"],
        user=UserInfo(id=19, username="prog_nightowl", pfp_url=""),
    ),
    EventOut(
        id=22,
        title="AI Ethics Talk",
        description="Discussing the future of AI.",
        date=date(2025, 7, 1),
        location="IC Auditorium",
        image_url="https://example.com/ai.jpg",
        is_public=True,
        departments=["Computer Science"],
        categories=["Talk"],
        clubs=["AMACSS"],
        types=["Discussion"],
        user=UserInfo(id=20, username="amacss_speaker", pfp_url=""),
    ),
    EventOut(
        id=23,
        title="CSEC Alumni Mixer",
        description="Reconnect with CSEC alumni.",
        date=date(2025, 6, 12),
        location="IC Lounge",
        image_url="https://example.com/mixer.jpg",
        is_public=True,
        departments=["Computer Science"],
        categories=["Networking"],
        clubs=["CSEC"],
        types=["Social"],
        user=UserInfo(id=4, username="csec_admin", pfp_url=""),
    ),
    EventOut(
        id=24,
        title="Open Source Intro",
        description="How to contribute to OSS.",
        date=date(2025, 6, 7),
        location="Online",
        image_url="https://example.com/oss.jpg",
        is_public=True,
        departments=["Computer Science"],
        categories=["Workshop"],
        clubs=["Programming Club"],
        types=["Tech"],
        user=UserInfo(id=6, username="prog_user", pfp_url=""),
    ),
    EventOut(
        id=25,
        title="Math Meet & Greet",
        description="Social event for new math students.",
        date=date(2025, 6, 3),
        location="SW-100",
        image_url="https://example.com/greet.jpg",
        is_public=True,
        departments=["Mathematics"],
        categories=["Social"],
        clubs=["Mathematics Club"],
        types=["Community"],
        user=UserInfo(id=23, username="math_mentor", pfp_url=""),
    ),
    EventOut(
        id=26,
        title="Cloud Computing Basics",
        description="Explore AWS and cloud tech.",
        date=date(2025, 6, 14),
        location="IC-401",
        image_url="https://example.com/cloud.jpg",
        is_public=True,
        departments=["Computer Science"],
        categories=["Tech"],
        clubs=["CSEC"],
        types=["Learning"],
        user=UserInfo(id=24, username="csec_user", pfp_url=""),
    ),
    EventOut(
        id=27,
        title="Advanced Algorithms",
        description="Dive deep into dynamic programming.",
        date=date(2025, 6, 25),
        location="IC-411",
        image_url="https://example.com/advanced_algo.jpg",
        is_public=True,
        departments=["Computer Science"],
        categories=["Lecture"],
        clubs=["Programming Club"],
        types=["Academic"],
        user=UserInfo(id=25, username="prog_advanced", pfp_url=""),
    ),
]
