from datetime import date
from schemas.event import EventOut
from schemas.user import UserInfo

mock_events = [
    EventOut(
        id=1,
        title="Spring Festival",
        description="A celebration of spring with food and music.",
        date=date(2025, 4, 15),
        location="Main Quad",
        image_url="https://marketplace.canva.com/EAFJMl8KcjI/1/0/1131w/canva-purple-black-tropical-party-club-poster-orVwDS2lrfY.jpg",
        is_public=True,
        departments=["Student Life"],
        categories=["Festival", "Music"],
        clubs=["Music Club"],
        types=["Social"],
        user=UserInfo(id=1, username="alice", pfp_url="https://art.ngfiles.com/images/2069000/2069032_nr-inko_mr-raven-pfp.png?f1631341251"),
    ),
    EventOut(
        id=2,
        title="Tech Talk: AI Trends",
        description="A talk on the latest in AI.",
        date=date(2025, 5, 10),
        location="Engineering Hall 101",
        image_url="https://marketplace.canva.com/EAFJMl8KcjI/1/0/1131w/canva-purple-black-tropical-party-club-poster-orVwDS2lrfY.jpg",
        is_public=False,
        departments=["Engineering"],
        categories=["Talk", "Technology"],
        clubs=["AI Club"],
        types=["Educational"],
        user=UserInfo(id=2, username="bob", pfp_url="https://art.ngfiles.com/images/2069000/2069032_nr-inko_mr-raven-pfp.png?f1631341251"),
    ),
    EventOut(
        id=3,
        title="Charity Run",
        description="5K run for local charities.",
        date=date(2025, 6, 1),
        location="City Park",
        image_url="https://marketplace.canva.com/EAFJMl8KcjI/1/0/1131w/canva-purple-black-tropical-party-club-poster-orVwDS2lrfY.jpg",
        is_public=True,
        departments=["Athletics"],
        categories=["Sports", "Charity"],
        clubs=["Running Club"],
        types=["Fundraiser"],
        user=UserInfo(id=3, username="carol", pfp_url="https://art.ngfiles.com/images/2069000/2069032_nr-inko_mr-raven-pfp.png?f1631341251"),
    ),
    EventOut(
        id=4,
        title="Art Exhibition",
        description="Showcasing student artwork.",
        date=date(2025, 5, 20),
        location="Art Center",
        image_url="https://marketplace.canva.com/EAFJMl8KcjI/1/0/1131w/canva-purple-black-tropical-party-club-poster-orVwDS2lrfY.jpg",
        is_public=True,
        departments=["Arts"],
        categories=["Exhibition", "Art"],
        clubs=["Art Club"],
        types=["Cultural"],
        user=UserInfo(id=4, username="dana", pfp_url="https://art.ngfiles.com/images/2069000/2069032_nr-inko_mr-raven-pfp.png?f1631341251"),
    ),
    EventOut(
        id=5,
        title="Career Fair",
        description="Meet recruiters from top companies.",
        date=date(2025, 9, 15),
        location="Convention Center",
        image_url="https://marketplace.canva.com/EAFJMl8KcjI/1/0/1131w/canva-purple-black-tropical-party-club-poster-orVwDS2lrfY.jpg",
        is_public=True,
        departments=["Career Services"],
        categories=["Fair", "Networking"],
        clubs=[],
        types=["Professional"],
        user=UserInfo(id=5, username="edward", pfp_url="https://art.ngfiles.com/images/2069000/2069032_nr-inko_mr-raven-pfp.png?f1631341251"),
    ),
    EventOut(
        id=6,
        title="Movie Night",
        description="Outdoor screening of a popular movie.",
        date=date(2025, 7, 10),
        location="Campus Lawn",
        image_url="https://marketplace.canva.com/EAFJMl8KcjI/1/0/1131w/canva-purple-black-tropical-party-club-poster-orVwDS2lrfY.jpg",
        is_public=True,
        departments=["Student Life"],
        categories=["Movie", "Entertainment"],
        clubs=["Film Club"],
        types=["Social"],
        user=UserInfo(id=6, username="fiona", pfp_url="https://art.ngfiles.com/images/2069000/2069032_nr-inko_mr-raven-pfp.png?f1631341251"),
    ),
    EventOut(
        id=7,
        title="Coding Bootcamp",
        description="Intensive weekend coding workshop.",
        date=date(2025, 8, 5),
        location="Tech Lab",
        image_url="https://marketplace.canva.com/EAFJMl8KcjI/1/0/1131w/canva-purple-black-tropical-party-club-poster-orVwDS2lrfY.jpg",
        is_public=False,
        departments=["Computer Science"],
        categories=["Workshop", "Technology"],
        clubs=["Coding Club"],
        types=["Educational"],
        user=UserInfo(id=7, username="george", pfp_url="https://art.ngfiles.com/images/2069000/2069032_nr-inko_mr-raven-pfp.png?f1631341251"),
    ),
    EventOut(
        id=8,
        title="Open Mic Night",
        description="Share your talent on stage.",
        date=date(2025, 6, 18),
        location="Student Union",
        image_url="https://marketplace.canva.com/EAFJMl8KcjI/1/0/1131w/canva-purple-black-tropical-party-club-poster-orVwDS2lrfY.jpg",
        is_public=True,
        departments=["Student Life"],
        categories=["Performance", "Music"],
        clubs=["Drama Club"],
        types=["Social"],
        user=UserInfo(id=8, username="hannah", pfp_url="https://art.ngfiles.com/images/2069000/2069032_nr-inko_mr-raven-pfp.png?f1631341251"),
    ),
    EventOut(
        id=9,
        title="Science Fair",
        description="Student science projects on display.",
        date=date(2025, 10, 2),
        location="Science Building",
        image_url="https://marketplace.canva.com/EAFJMl8KcjI/1/0/1131w/canva-purple-black-tropical-party-club-poster-orVwDS2lrfY.jpg",
        is_public=True,
        departments=["Science"],
        categories=["Fair", "Education"],
        clubs=["Science Club"],
        types=["Educational"],
        user=UserInfo(id=9, username="ian", pfp_url="https://art.ngfiles.com/images/2069000/2069032_nr-inko_mr-raven-pfp.png?f1631341251"),
    ),
    EventOut(
        id=10,
        title="Food Truck Rally",
        description="Enjoy food from local vendors.",
        date=date(2025, 5, 30),
        location="Parking Lot B",
        image_url="https://marketplace.canva.com/EAFJMl8KcjI/1/0/1131w/canva-purple-black-tropical-party-club-poster-orVwDS2lrfY.jpg",
        is_public=True,
        departments=["Student Life"],
        categories=["Food", "Festival"],
        clubs=[],
        types=["Social"],
        user=UserInfo(id=10, username="julia", pfp_url="https://art.ngfiles.com/images/2069000/2069032_nr-inko_mr-raven-pfp.png?f1631341251"),
    ),
]