sample_events = [
    {
        "id": 49,
        "title": "Hack the Future",
        "description": "A hackathon for all skill levels.",
        "date": "2025-07-20T00:00:00Z",
        "location": "IC Building, Room 402",
        "image_url": "https://marketplace.canva.com/EAFJMl8KcjI/1/0/1131w/canva-purple-black-tropical-party-club-poster-orVwDS2lrfY.jpg",
        "user": {
            "id": 1,
            "username": "amacss_admin",
            "pfp_url": "https://example.com/pfp1.jpg",
            "is_verified": False,
        },
    },
    {
        "id": 59,
        "title": "Game Jam 2025",
        "description": "24-hour game dev event.",
        "date": "2025-07-10T00:00:00Z",
        "location": "IC Atrium",
        "image_url": "https://marketplace.canva.com/EAFJMl8KcjI/1/0/1131w/canva-purple-black-tropical-party-club-poster-orVwDS2lrfY.jpg",
        "user": {
            "id": 9,
            "username": "prog_master",
            "pfp_url": "https://example.com/pfp9.jpg",
            "is_verified": False,
        },
    },
    {
        "id": 65,
        "title": "Data Science Demystified",
        "description": "Intro to data science methods.",
        "date": "2025-07-05T00:00:00Z",
        "location": "IC 110",
        "image_url": "https://marketplace.canva.com/EAFJMl8KcjI/1/0/1131w/canva-purple-black-tropical-party-club-poster-orVwDS2lrfY.jpg",
        "user": {
            "id": 15,
            "username": "ds_talker",
            "pfp_url": "https://example.com/pfp15.jpg",
            "is_verified": False,
        },
    },
    {
        "id": 70,
        "title": "AI Ethics Talk",
        "description": "Discussing the future of AI.",
        "date": "2025-07-01T00:00:00Z",
        "location": "IC Auditorium",
        "image_url": "https://marketplace.canva.com/EAFJMl8KcjI/1/0/1131w/canva-purple-black-tropical-party-club-poster-orVwDS2lrfY.jpg",
        "user": {
            "id": 20,
            "username": "amacss_speaker",
            "pfp_url": "https://example.com/pfp20.jpg",
            "is_verified": False,
        },
    },
    {
        "id": 62,
        "title": "Algorithm Workshop",
        "description": "Learn sorting algorithms.",
        "date": "2025-06-30T00:00:00Z",
        "location": "IC-312",
        "image_url": "https://marketplace.canva.com/EAFJMl8KcjI/1/0/1131w/canva-purple-black-tropical-party-club-poster-orVwDS2lrfY.jpg",
        "user": {
            "id": 12,
            "username": "prog_user",
            "pfp_url": "https://example.com/pfp12.jpg",
            "is_verified": False,
        },
    },
    {
        "id": 64,
        "title": "Code Golf Night",
        "description": "Solve problems with the shortest code.",
        "date": "2025-06-27T00:00:00Z",
        "location": "IC Lab 1",
        "image_url": "https://marketplace.canva.com/EAFJMl8KcjI/1/0/1131w/canva-purple-black-tropical-party-club-poster-orVwDS2lrfY.jpg",
        "user": {
            "id": 14,
            "username": "golf_guru",
            "pfp_url": "https://example.com/pfp14.jpg",
            "is_verified": False,
        },
    },
    {
        "id": 75,
        "title": "Advanced Algorithms",
        "description": "Dive deep into dynamic programming.",
        "date": "2025-06-25T00:00:00Z",
        "location": "IC-411",
        "image_url": "https://marketplace.canva.com/EAFJMl8KcjI/1/0/1131w/canva-purple-black-tropical-party-club-poster-orVwDS2lrfY.jpg",
        "user": {
            "id": 25,
            "username": "prog_advanced",
            "pfp_url": "https://example.com/pfp25.jpg",
            "is_verified": False,
        },
    },
    {
        "id": 58,
        "title": "Git and GitHub Basics",
        "description": "Learn version control with Git.",
        "date": "2025-06-22T00:00:00Z",
        "location": "IC-410",
        "image_url": "https://marketplace.canva.com/EAFJMl8KcjI/1/0/1131w/canva-purple-black-tropical-party-club-poster-orVwDS2lrfY.jpg",
        "user": {
            "id": 8,
            "username": "csec_member1",
            "pfp_url": "https://example.com/pfp8.jpg",
            "is_verified": False,
        },
    },
    {
        "id": 69,
        "title": "Late Night Leetcode",
        "description": "Group problem solving session.",
        "date": "2025-06-20T00:00:00Z",
        "location": "IC Lab 2",
        "image_url": "https://marketplace.canva.com/EAFJMl8KcjI/1/0/1131w/canva-purple-black-tropical-party-club-poster-orVwDS2lrfY.jpg",
        "user": {
            "id": 19,
            "username": "prog_nightowl",
            "pfp_url": "https://example.com/pfp19.jpg",
            "is_verified": False,
        },
    },
    {
        "id": 54,
        "title": "Cybersecurity Basics",
        "description": "Workshop on staying safe online.",
        "date": "2025-06-18T00:00:00Z",
        "location": "IC Lab 3",
        "image_url": "https://marketplace.canva.com/EAFJMl8KcjI/1/0/1131w/canva-purple-black-tropical-party-club-poster-orVwDS2lrfY.jpg",
        "user": {
            "id": 4,
            "username": "csec_admin",
            "pfp_url": "https://example.com/pfp4.jpg",
            "is_verified": False,
        },
    },
    {
        "id": 51,
        "title": "Coding Bootcamp",
        "description": "Beginner-friendly JavaScript course.",
        "date": "2025-06-15T00:00:00Z",
        "location": "Online (Zoom)",
        "image_url": "https://marketplace.canva.com/EAFJMl8KcjI/1/0/1131w/canva-purple-black-tropical-party-club-poster-orVwDS2lrfY.jpg",
        "user": {
            "id": 3,
            "username": "csec_lead",
            "pfp_url": "https://example.com/pfp3.jpg",
            "is_verified": False,
        },
    },
    {
        "id": 74,
        "title": "Cloud Computing Basics",
        "description": "Explore AWS and cloud tech.",
        "date": "2025-06-14T00:00:00Z",
        "location": "IC-401",
        "image_url": "https://marketplace.canva.com/EAFJMl8KcjI/1/0/1131w/canva-purple-black-tropical-party-club-poster-orVwDS2lrfY.jpg",
        "user": {
            "id": 24,
            "username": "cloud_fan",
            "pfp_url": "https://example.com/pfp24.jpg",
            "is_verified": False,
        },
    },
    {
        "id": 71,
        "title": "CSEC Alumni Mixer",
        "description": "Reconnect with CSEC alumni.",
        "date": "2025-06-12T00:00:00Z",
        "location": "IC Lounge",
        "image_url": "https://marketplace.canva.com/EAFJMl8KcjI/1/0/1131w/canva-purple-black-tropical-party-club-poster-orVwDS2lrfY.jpg",
        "user": {
            "id": 21,
            "username": "csec_alumni",
            "pfp_url": "https://example.com/pfp21.jpg",
            "is_verified": False,
        },
    },
    {
        "id": 67,
        "title": "Intro to Web Dev",
        "description": "Learn HTML/CSS/JS basics.",
        "date": "2025-06-11T00:00:00Z",
        "location": "IC-406",
        "image_url": "https://marketplace.canva.com/EAFJMl8KcjI/1/0/1131w/canva-purple-black-tropical-party-club-poster-orVwDS2lrfY.jpg",
        "user": {
            "id": 17,
            "username": "web_starter",
            "pfp_url": "https://example.com/pfp17.jpg",
            "is_verified": False,
        },
    },
    {
        "id": 50,
        "title": "Math Puzzle Night",
        "description": "Collaborative math challenges and prizes.",
        "date": "2025-06-10T00:00:00Z",
        "location": "Science Wing 115",
        "image_url": "https://marketplace.canva.com/EAFJMl8KcjI/1/0/1131w/canva-purple-black-tropical-party-club-poster-orVwDS2lrfY.jpg",
        "user": {
            "id": 2,
            "username": "math_user",
            "pfp_url": "https://example.com/pfp2.jpg",
            "is_verified": False,
        },
    },
    {
        "id": 60,
        "title": "Math Careers Panel",
        "description": "Hear from alumni in math careers.",
        "date": "2025-06-08T00:00:00Z",
        "location": "Science Lecture Hall",
        "image_url": "https://marketplace.canva.com/EAFJMl8KcjI/1/0/1131w/canva-purple-black-tropical-party-club-poster-orVwDS2lrfY.jpg",
        "user": {
            "id": 10,
            "username": "career_math",
            "pfp_url": "https://example.com/pfp10.jpg",
            "is_verified": False,
        },
    },
    {
        "id": 72,
        "title": "Open Source Intro",
        "description": "How to contribute to OSS.",
        "date": "2025-06-07T00:00:00Z",
        "location": "Online",
        "image_url": "https://marketplace.canva.com/EAFJMl8KcjI/1/0/1131w/canva-purple-black-tropical-party-club-poster-orVwDS2lrfY.jpg",
        "user": {
            "id": 22,
            "username": "oss_helper",
            "pfp_url": "https://example.com/pfp22.jpg",
            "is_verified": False,
        },
    },
    {
        "id": 55,
        "title": "Python Practice",
        "description": "Solve coding challenges in Python.",
        "date": "2025-06-05T00:00:00Z",
        "location": "IC 404",
        "image_url": "https://marketplace.canva.com/EAFJMl8KcjI/1/0/1131w/canva-purple-black-tropical-party-club-poster-orVwDS2lrfY.jpg",
        "user": {
            "id": 5,
            "username": "prog_enthusiast",
            "pfp_url": "https://example.com/pfp5.jpg",
            "is_verified": False,
        },
    },
    {
        "id": 73,
        "title": "Math Meet & Greet",
        "description": "Social event for new math students.",
        "date": "2025-06-03T00:00:00Z",
        "location": "SW-100",
        "image_url": "https://marketplace.canva.com/EAFJMl8KcjI/1/0/1131w/canva-purple-black-tropical-party-club-poster-orVwDS2lrfY.jpg",
        "user": {
            "id": 23,
            "username": "math_mentor",
            "pfp_url": "https://example.com/pfp23.jpg",
            "is_verified": False,
        },
    },
    {
        "id": 63,
        "title": "Math Research Talk",
        "description": "Undergraduate math research showcase.",
        "date": "2025-06-02T00:00:00Z",
        "location": "SW-205",
        "image_url": "https://marketplace.canva.com/EAFJMl8KcjI/1/0/1131w/canva-purple-black-tropical-party-club-poster-orVwDS2lrfY.jpg",
        "user": {
            "id": 13,
            "username": "math_speaker",
            "pfp_url": "https://example.com/pfp13.jpg",
            "is_verified": False,
        },
    },
    {
        "id": 52,
        "title": "Speed Coding Challenge",
        "description": "Code fast, win prizes!",
        "date": "2025-06-01T00:00:00Z",
        "location": "IC-402",
        "image_url": "https://marketplace.canva.com/EAFJMl8KcjI/1/0/1131w/canva-purple-black-tropical-party-club-poster-orVwDS2lrfY.jpg",
        "user": {
            "id": 1,
            "username": "amacss_admin",
            "pfp_url": "https://example.com/pfp1.jpg",
            "is_verified": False,
        },
    },
    {
        "id": 66,
        "title": "Discrete Math Review",
        "description": "Finals prep session for MATB24.",
        "date": "2025-06-01T00:00:00Z",
        "location": "SW-112",
        "image_url": "https://marketplace.canva.com/EAFJMl8KcjI/1/0/1131w/canva-purple-black-tropical-party-club-poster-orVwDS2lrfY.jpg",
        "user": {
            "id": 16,
            "username": "math_ta",
            "pfp_url": "https://example.com/pfp16.jpg",
            "is_verified": False,
        },
    },
    {
        "id": 68,
        "title": "Functional Programming",
        "description": "Haskell intro night.",
        "date": "2025-05-30T00:00:00Z",
        "location": "Online",
        "image_url": "https://marketplace.canva.com/EAFJMl8KcjI/1/0/1131w/canva-purple-black-tropical-party-club-poster-orVwDS2lrfY.jpg",
        "user": {
            "id": 18,
            "username": "fp_dev",
            "pfp_url": "https://example.com/pfp18.jpg",
            "is_verified": False,
        },
    },
    {
        "id": 53,
        "title": "Math Jeopardy!",
        "description": "Test your math skills in a Jeopardy format.",
        "date": "2025-05-28T00:00:00Z",
        "location": "SW-105",
        "image_url": "https://marketplace.canva.com/EAFJMl8KcjI/1/0/1131w/canva-purple-black-tropical-party-club-poster-orVwDS2lrfY.jpg",
        "user": {
            "id": 2,
            "username": "math_user",
            "pfp_url": "https://example.com/pfp2.jpg",
            "is_verified": False,
        },
    },
    {
        "id": 61,
        "title": "Women in Tech Panel",
        "description": "Empowering women in CS.",
        "date": "2025-05-25T00:00:00Z",
        "location": "Online",
        "image_url": "https://marketplace.canva.com/EAFJMl8KcjI/1/0/1131w/canva-purple-black-tropical-party-club-poster-orVwDS2lrfY.jpg",
        "user": {
            "id": 11,
            "username": "women_cs",
            "pfp_url": "https://example.com/pfp11.jpg",
            "is_verified": False,
        },
    },
    {
        "id": 56,
        "title": "Intro to Linux",
        "description": "A past event teaching Linux basics.",
        "date": "2025-03-15T00:00:00Z",
        "location": "SW-210",
        "image_url": "https://marketplace.canva.com/EAFJMl8KcjI/1/0/1131w/canva-purple-black-tropical-party-club-poster-orVwDS2lrfY.jpg",
        "user": {
            "id": 6,
            "username": "techie_tim",
            "pfp_url": "https://example.com/pfp6.jpg",
            "is_verified": False,
        },
    },
    {
        "id": 57,
        "title": "Fun with Logic",
        "description": "Math games based on logical reasoning.",
        "date": "2025-02-28T00:00:00Z",
        "location": "SW-120",
        "image_url": "https://marketplace.canva.com/EAFJMl8KcjI/1/0/1131w/canva-purple-black-tropical-party-club-poster-orVwDS2lrfY.jpg",
        "user": {
            "id": 7,
            "username": "math_admin",
            "pfp_url": "https://example.com/pfp7.jpg",
            "is_verified": False,
        },
    },
]
