name: Server CI (Local Only)

on:
  workflow_call:
  local-test::

jobs:
  test-server:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build server Docker image
      run: docker build -t fastapi-app ./server

    - name: Run tests inside Docker
      run: docker run -e DATABASE_URL=$DATABASE_URL --network=host fastapi-app pytest

