name: Server CI

on:
  pull_request:
    branches:
      - main
      - developing

jobs:
  test-server:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build server Docker image
      run: docker build -t fastapi-app ./server

    - name: Run tests inside Docker
      run: docker run -e DATABASE_URL=${{ secrets.DATABASE_URL }} --network=host fastapi-app pytest


