name: Server CI

on:
  push:

jobs:
  test-server:
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build server Docker image
      run: docker build -t fastapi-app ./server

    - name: Run tests inside Docker
      run: docker run --env-file server/.secret --network=host fastapi-app pytest