name: Server CI

on:
  pull_request:
    branches:
      - developing
      - main

jobs:
  test-server:
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        working-directory: server

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Supabase CLI
      run: |
        mkdir -p /tmp/supabase-cli
        curl -sL https://github.com/supabase/cli/releases/latest/download/supabase_linux_amd64.tar.gz | tar -xz -C /tmp/supabase-cli
        sudo mv /tmp/supabase-cli/supabase /usr/local/bin/supabase


    - name: Start Supabase services
      run: supabase start

    - name: Wait for Supabase to be ready
      run: |
        for i in {1..10}; do
          pg_isready -h localhost -p 54322 && break
          echo "Waiting for Supabase DB..."
          sleep 3
        done

    - name: Seed Database
      run: supabase db seed

    - name: Build server Docker image
      run: docker build -t fastapi-app .

    - name: Run tests inside Docker
      run: |
        docker run --rm \
          --add-host=host.docker.internal:host-gateway \
          -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
          fastapi-app pytest





