name: Server CI

on:
  pull_request:
    branches:
      - developing
      - main

jobs:
  test-server:
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build server Docker image
      run: docker build -t fastapi-app ./server

    - name: Run tests inside Docker
      run: |
        docker run --rm \
          --add-host=host.docker.internal:host-gateway \
          -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
          fastapi-app pytest
